sudo: required
services:
  - docker


  #- ./deploy.sh
  # Log in to docker cli
  #- echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  #- docker push swording/multi-client
  #- docker push swording/multi-nginx
  #- docker push swording/multi-server
  #- docker push swording/multi-worker
deploy:
  provider: script
  script: echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  on:
    branch: master
  